name: CPP BootUp CI

on:
  push:
    branches: [ main ]

jobs:
  UWB_CPP_BootUp_CI:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: .github/workflows/install_dependencies.sh
      - name: Create Makefile
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
      - name: Build code
        run: make -j4
      - name: Run unit tests
        run: make function_tests # run all executables ending with "_test"
      - name: Run memory tests
        run: .github/workflows/memcheck.sh
      - name: Cheer!
        run: bash .github/workflows/success.sh
